## configs for api-gateway services
automation:
  http:
    rest-client:
 #     - active: true
        url: http://localhost:8081/v1
        name: api-gateway-1
        headers:        #optional
          Accept: application/json
        #root: /v1       #optional --> this should be part of url
    rest-client:
        url: http://localhost:8081/v2
        name: api-gateway-2
        headers:        #optional
          Accept: application/json
      #root: /v1       #optional --> this should be part of url